services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=carlease'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=admin'
    ports:
      - '5432:5432'
    volumes:
      - "./src/main/resources/scripts:/docker-entrypoint-initdb.d"
